### ISSUE TITLE
chargebar issues

### ISSUE THREAD

**Issue by r3dnasa** [Hypnootize/m0rehud#14]
1. spies chargebar for the sapper in mvm overlaps the disguisestatus making it hard to see.

2. soldiers banner chargebar and the bison chargebar are not at the same y level making it look inconsistent even though they take up the same item slot and makes the banner bar look off when used with the cow mangler.

3. (i know this is a bit of a nitpick but) the base chargebar huditemeffectmeter.res overlaps with the mvm round countdown timer which is annoying 

4. the chargebar for the snipers hitmans heatmaker i feel should be lowered by changing the base to `#base "huditemeffectmeter_scout.res"`

**Comment by Hypnootize** [comment]
1. I can't really find a good solution for this, I really want to keep the disguise panel where it is, as it's been there for 10+ years, and it's something people look for, at the same time there isn't really a better place for the sapper as even moving it down will make it overlap with the MvM progress bar. To be fair I also value the sapper meter as something way less important compared to the disguise panel, as it only appears in MvM.

2. That's something I can't do too much about, the bison meter is exactly where it should be but the banners aren't, the reason for that is HUDItemEffectMeter.res handeling a bunch of different meters with different weapons slots within a single file so fixing it for soldier will ruin it the positioning for other classes as well and viceversa.

3. That should now be fixed

4. If you use the same logic as the n2 point the hitmans heatmaker is currently in the slot it should be.

**Comment by Hypnootize** [comment]
`m0rehud 7.0` introduces some customizations that should help solve this problem, precisely the disgusie panel can be moved to the bottom left to fix the MvM sapper overlapping now, the other meters should have a slightly better positioning now as well!
