### ISSUE TITLE
backpack menu issue

### ISSUE THREAD

**Issue by r3dnasa** [Hypnootize/m0rehud#17]
new item notif in the backback menu is cutoff partially
![20230512183501_1](https://github.com/Hypnootize/m0rehud/assets/82971054/812b919b-330b-4a3f-93f6-8814d7cff5d2)

**Comment by Hypnootize** [comment]
It should be fixed now!
![Backpack Button](https://github.com/Hypnootize/m0rehud/assets/19785551/72cb8f8d-189f-406b-89d1-5fef2493ae97)
