### ISSUE TITLE
Health and ammo shadows have different offsets in Minmode

### ISSUE THREAD

**Issue by qkeitoe** [Hypnootize/m0rehud#21]
![Screenshot (81)](https://github.com/Hypnootize/m0rehud/assets/66339491/1dc1d847-67fa-47d1-af05-ec9fe299d282)
![Screenshot (82)](https://github.com/Hypnootize/m0rehud/assets/66339491/78c3caac-cf6a-408a-8c24-b226263166e5)

**Comment by Hypnootize** [comment]
I honestly can't remember if there was a reason for me using a different offset for the ammo shadows. I assume both ammo and health shadows used an offset of `-1` but I then tweaked the health one to be a little more noticeable and forgot to update it for the ammo as well, I'll make the ammo shadows match the health now and I assume it will be fine.
