### ISSUE TITLE
Some panels in `TargetID` are shifted to the right

### ISSUE THREAD

**Issue by qkeitoe** [Hypnootize/m0rehud#22]
![Screenshot (83)](https://github.com/Hypnootize/m0rehud/assets/66339491/71a1b2a2-7a0d-443a-bb1b-0dd2b78def4d)

`TargetID` is perfectly centered by itself.

https://github.com/Hypnootize/m0rehud/blob/63464b4d2c005d16f9cdcabca1ec3f7968845a49/resource/ui/targetid.res#L3-L20
https://github.com/Hypnootize/m0rehud/blob/63464b4d2c005d16f9cdcabca1ec3f7968845a49/scripts/layouts/layout_default.res#L247-L261

I'm not sure if this was intended so I've opened an issue instead of a PR.

**Comment by qkeitoe** [comment]
I decided for myself to set the backgrounds to `"xpos" "0"` and the health to `"xpos" "5"`, kinda centering the health between the left edge and the name.

Minmode:
![Screenshot (91)](https://github.com/Hypnootize/m0rehud/assets/66339491/021288f6-6933-46ab-8212-8a74edf3cfeb)
Default:
![Screenshot (103)](https://github.com/Hypnootize/m0rehud/assets/66339491/b869cce9-016c-4ae5-adcc-2f6f8210f059)

Also, inspired by recent changes to [resource/ui/spectatorguihealth.res](https://github.com/Hypnootize/m0rehud/commit/00a85ca6db4f44f17123d117319fd093def0bd57#diff-0ba007b048c0ee17ec2691a81d57a2f8d5aadfb9db1203ceee73fd81cba34fec), I've come with the similar change to Minmode version by keeping `"xpos" "12"` and increasing both `"wide"` and `"tall"` of `"PlayerStatusHealthBonusImage"` to `"11"`. I'm not completely sure, but i guess it look better (although my eyes may be deceiving me).

Before:
![Screenshot (95)](https://github.com/Hypnootize/m0rehud/assets/66339491/48e31a82-61f4-422b-8304-7c7689d69e6a)
After:
![Screenshot (94)](https://github.com/Hypnootize/m0rehud/assets/66339491/6b81ba24-a3be-462f-bfd6-42ce294aadc5)

**Comment by qkeitoe** [comment]
Just to mention, I noticed the shift while i was on a jump server. It becomes really noticeable by being close to `"HudHintDisplay"`.
![Screenshot (105)](https://github.com/Hypnootize/m0rehud/assets/66339491/4d8f04e6-cd3a-4107-95f7-d89451477fd9).

**Comment by Hypnootize** [comment]
Yeah I think that's reasonable, I replicated and pushed the changes now!
I tweaked the bonus cross for the minmode as well and I ended up making it a bit bigger, it's a bit tricky with this font as it tends to look always a little off when the health is a single digit, seems mostly fine from what I've tested.
