### ISSUE TITLE
Toggle Chat button in gamemenu.res swaps to wrong value

### ISSUE THREAD

**Issue by czarchasm00** [Hypnootize/m0rehud#29]
By [default](https://developer.valvesoftware.com/wiki/List_of_Team_Fortress_2_console_commands_and_variables), `hud_saytext_time` is 12. However, on the Toggle Chat button in gamemenu.res, `hud_saytext_time` is set to 6. 

I recommend changing it to 12, as most users will have that value at 12 already.

**Comment by qkeitoe** [comment]
mastercomfig has `hud_saytext_time` set to [10](https://github.com/mastercomfig/mastercomfig/blob/7012f09935caca6f3553298c355f4b9503764953/config/mastercomfig/cfg/comfig/comfig.cfg#L1125) by default (except Very Low preset).

**Comment by Hypnootize** [comment]
I have always felt like 12 was a bit too high, so that's where `hud_saytext_time 6` is coming from. To be fair I'm fine with either and I see how having it set to the default value could benefit the majority of players.
It should toggle it between `0` and `12` now!
