### ISSUE TITLE
%20 instead of a space causes transparent viewmodels to stop working

### ISSUE THREAD

**Issue by czarchasm00** [Hypnootize/m0rehud#30]
I'm not sure why, or how, but I've had it happen twice now (with different versions of m0rehud) where hudlayout.res is the source of my issue for transparent viewmodels not working. It has to do with the %20 that is used instead of a space. If I remove the %20 and put a space, my transparent viewmodels instantly start working again once I use hud_reloadscheme.

I'd like to say I remember it working yesterday when I was using this hud? But I didn't pay attention to that part so I can't be 100% sure.
Regardless, I'd like to ask why is a %20 used there instead of just a space?

**Comment by Hypnootize** [comment]
Yeah seem like the script I used adds the `%20` if there is a space in the link, I didn't notice it and it should be fixed now!
