### ISSUE TITLE
Vaccinator ubercharge meter

### ISSUE THREAD

**Issue by miyho** [Hypnootize/m0rehud#32]
its broken, everytime i use it the ubercharge meter freezes on whatever charge was the last medi gun i used.

**Comment by Hypnootize** [comment]
It's a problem with how Valve designed the vaccinator elements, in short you can't have more than one uber label, every custom created one will also show when the vaccinator is active and will display the last amount of ubercharge you had.

There really isn't a good solution to this other than only keeping the default label, which you can do with the `customizations/Health Ammo Uber Style/[Ubercharge] Old m0rehud Style` customization.

as to why I the customization isn't enable by default the main reason is that I'd like to keep the uberchange style as it is personally, as I value it to be more important than the least used vaccinator, sadly there isn't a solution that suites both.

**Comment by miyho** [comment]
thanks ur awesome
