### ISSUE TITLE
m0rehud update causes you to go to Items screen first if preloading

### ISSUE THREAD

**Issue by czarchasm00** [Hypnootize/m0rehud#33]
What happens:
Boot up TF2, then wait for preloading to finish and see the Items screen pop up. You have to press back to get out of it like normal.

To replicate:
Put 'map itemtest; wait 5; disconnect; wait 3;' in your autoexec.cfg as shown in screenshot. The error will happen. Next, remove the line, save, and launch TF2 like normal. It will not jump to the items screen first.

I tested this by enabling and disabling preloading both in mastercomfig and through the old-fashioned way. It does not matter what map you use.

My previous version of m0rehud was 6.4, updated to commit [88be507](https://github.com/Hypnootize/m0rehud/commit/88be5075c19d34548b7c1133c57938ddfe25e277). This error was introduced sometime after that commit.

![1](https://github.com/Hypnootize/m0rehud/assets/76140847/d01daad4-b602-464d-a6d4-5fe03fcdf4bc)

**Comment by Hypnootize** [comment]
This should be fixed with the last update
