### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by czarchasm00** [Hypnootize/m0rehud#34]
![1](https://github.com/Hypnootize/m0rehud/assets/76140847/bb2cca09-317c-44a5-a28d-fcd9bf61a52f)
Should be "Information" not "Informations"

Wiki:
![2](https://github.com/Hypnootize/m0rehud/assets/76140847/eeedde11-afa0-4ad1-b34c-c67bf51b990e)
![zjSFZq4k3P](https://github.com/Hypnootize/m0rehud/assets/76140847/7795d8a3-bfc6-4522-a7d9-74a7743edaef)
Should be "its" instead of "it's"

![NxZVAAdJUi](https://github.com/Hypnootize/m0rehud/assets/76140847/3fc8ba0d-08a9-4868-9108-3b87b45e9c27)
Should be "extracting" instead of "extractin"

Those are just the ones I noticed most.

**Comment by Hypnootize** [comment]
I was half asleep when I wrote some of the wiki pages so I expect about 1000 more typos to be there, thanks for reporting those, the wiki is fixed and I'll update the "Informations" typo later
