### ISSUE TITLE
Potential customization ideas

### ISSUE THREAD

**Issue by czarchasm00** [Hypnootize/m0rehud#35]
Just wanted to throw these out there, see what you thought.

Idea 1:
Moving sniper scope charge over to the right
https://github.com/czarchasm00/m0rehud-cz/commit/186c9562d5980e886a75796ed96e1005c38cc073
Pretty basic, but it technically has less clutter inside the scope, and it's a simple swap. May be preferred for some competitive minded players.
Before:
![1](https://github.com/Hypnootize/m0rehud/assets/76140847/ce517d1c-493b-4415-ae13-e0b0d9728e70)
After:
![2](https://github.com/Hypnootize/m0rehud/assets/76140847/1aa73f12-69d8-4859-9296-aab50a96f100)

Idea 2:
Modifying textwindow.res for proper visibility of logs.tf.
Logs.tf is a website where 99% of logs from competitive matches are uploaded to.
As it stands now, if you open up logs.tf in-game by typing .ss after a match, it displays about half of the page. We have to scroll over in order to properly read the logs, which is kind of annoying.
![1](https://github.com/Hypnootize/m0rehud/assets/76140847/f0b8ceb9-fafb-4d1b-a6dc-817ac50e3396)
By simply modifying the wide and tall values on TFTextMessage and HTMLMessage like so:
https://github.com/czarchasm00/m0rehud-cz/commit/1c12a56507bc732f5e135a7c31a913449cabbcf2
We can now view most of the entire page easily!
![2](https://github.com/Hypnootize/m0rehud/assets/76140847/2a0a49f8-3b27-4840-8431-736c64a3f6ae)
This will likely have to be changed based on your aspect ratio, but I'm not familiar with that type of work.

Let me know what you all think!

**Comment by Hypnootize** [comment]
I have implemented the larger MOTD panel by default with the last update, I see no reason to have it as customization as I think it's way better having it on by default. 
As for the sniper scope I'm not sure if it's worth adding it as a customizations, I expect something like this to be pretty niche but I'm fine with adding it in the future if there is enough request, for now I'll make sure to add a wiki page for it!
