### ISSUE TITLE
Potential customization for `ControlPointProgressBar`

### ISSUE THREAD

**Issue by qkeitoe** [Hypnootize/m0rehud#38]
What do you think about adding a customization option to enable `ControlPointProgressBar` in the bottom right corner? Something like shown on the screenshots (they were made with [JackyLegs](https://steamcommunity.com/id/JackyLegss/)' sunsethudv2)
![Screenshot (5)](https://github.com/Hypnootize/m0rehud/assets/66339491/b1a7e436-06b4-4402-a605-16e4200d3b31)
![Screenshot (6)](https://github.com/Hypnootize/m0rehud/assets/66339491/099d064f-23c0-409b-84d9-e2cc6b40c193)

**Comment by Hypnootize** [comment]
That would also be an interesting addition, I'll keep it in mind!
I might actually open a dedicated pinned issue where everyone can post their ideas for future customizations, just so I can keep better track of everything.

**Comment by Hypnootize** [comment]
Closing as this is now implemented and part of the master branch.
