### ISSUE TITLE
Teleportation count missing

### ISSUE THREAD

**Issue by Frotty** [Hypnootize/m0rehud#4]
Hi, thanks for the great HUD.
One small annoyance for me is that when playing engineer, the amount of teleportations done with your teleporter isn't shown as it is on vanilla HUD or most other HUDs.
![](https://i.imgur.com/80erj80.png)
It would be nice if this could be re added

**Comment by Frotty** [comment]
Thanks for the fix, works nicely now!

Quick Question: Will you continue this HUD too or just your new project https://github.com/Hypnootize/Hypnotize-m0rehud ?

**Comment by Hypnootize** [comment]
I'll keep it updated if i can but I don't know if i'll ever add new stuff to it.
