### ISSUE TITLE
[ISSUE] MvM Layout Breaks

### ISSUE THREAD

**Issue by notkiniro** [Hypnootize/m0rehud#45]
![Screenshot_2023-11-13_12-22-08](https://github.com/Hypnootize/m0rehud/assets/150722464/192235db-0831-4f41-baf1-f156d0ff2e69)
Using the default resolution.

**Comment by notkiniro** [comment]
Reloading the hud via **hud_reloadscheme** doesn't seem to be fixing it.

**Comment by Hypnootize** [comment]
I'm aware of this problem but I can't seem to be able to reproduce it in a constant way, it just sort of happens every now and then, which translates in me not really knowing what could be causing it exactly. I can't recall changing anything that would affect which panel is prioritized over the others but it's TF2 so could be anything.

A potential fix could be increasing the `"zpos"` of `"MvMCriteria"` inside `Resource/UI/MatchMakingDashboardMvMCriteria.res`, bumping it from `"1002"` to `"1003"` will be enough to make sure it displays over the MvM mode selection panel no matter what. Not sure if that could cause any other side effect but I don't think it should.

**Comment by Hypnootize** [comment]
This should now be fixed with https://github.com/Hypnootize/m0rehud/commit/6c3e4c521def41e4c0a0e04049004d9d78f191ef
