### ISSUE TITLE
Changes won't apply when I reload. 

### ISSUE THREAD

**Issue by Pepcen** [Hypnootize/m0rehud#46]
That's it. That's the issue.

**Comment by Pepcen** [comment]
> Are you on windows? and if yes what kind of changes did you try to make?

Sorry for the late reply. I'm on windows 10. I tried changing crosshairs, turning on player model and a few others.

**Comment by Hypnootize** [comment]
I think the most likely cause is that you might have another `valve.rc` file inside your custom folder which conflicts with the one from m0rehud. You can fix that by adding `exec m0re_customization.cfg` inside your `autoexec.res` if that's the case.

**Comment by Pepcen** [comment]
> I think the most likely cause is that you might have another `valve.rc` file inside your custom folder which conflicts with the one from m0rehud. You can fix that by adding `exec m0re_customization.cfg` inside your `autoexec.res` if that's the case.

It's working now :D Thanks a lot <3

**Comment by Pepcen** [comment]
Fixed
