### ISSUE TITLE
Can I bind keys to change crosshairs?

### ISSUE THREAD

**Issue by Pepcen** [Hypnootize/m0rehud#47]
This might not be what issues are for idk.

**Comment by Hypnootize** [comment]
If you are referring to the HUD Crosshairs then yes it's possible but I wouldn't advise it, the only way to show the crosshair changes is by reloading the HUD with `hud_reloadsheme` which come with the side effect of freezing the game for a second or two which is far from optimal.
If you are looking to have a couple of separate keys binded to switch between different crosshairs every now and then it should be fine, but if you are looking to switch crosshair base on what weapon you are on then it's an extremely inefficient way of doing it, you can get a much better result with the use of [VTF Crosshairs](https://cfg.tf/tools/crosshairs)
