### ISSUE TITLE
[bug] m0rehud crosshairs arent showing but vanilla ones do

### ISSUE THREAD

**Issue by dxcvvxd** [Hypnootize/m0rehud#53]
no amount of resets helps, im really puzzled at what can cause this and there's nothing about it in the wiki
also i should mention that i've used toonhud before this one so maybe that the issue

**Comment by Hypnootize** [comment]
HUD Crosshairs seem to be working fine on my end. Are any of the other customization working? if not try adding this line `exec m0re_customization.cfg` to your `autoexec.cfg`. Also are you on windows?

**Comment by dxcvvxd** [comment]
im on linux, and all my customizations are as follows:
![image](https://github.com/Hypnootize/m0rehud/assets/77129815/be57e598-4020-4905-a264-0fb3e4a10b12)
(idk if thats a mastercomfig issue)

**Comment by Hypnootize** [comment]
mastercomfig shouldn't impact the HUD as far as I know. There is a dedicated branch for a m0rehud linux version, are you already using that one? Here: https://github.com/Hypnootize/m0rehud/tree/linux it has some tweaks to make customizations work on linux. 

Also I'm not too knowledgeable on how HUDs work on linux but I assume you should't have two HUDs in your custom folder regardless so I would probably take the toonhud folder out.

**Comment by dxcvvxd** [comment]
i know about conflicts but i have toonhud hidden from the game so only m0rehud works
and no, i didnt know there was a linux version lol, i thought tf2 mods work regardless of platform

**Comment by dxcvvxd** [comment]
ok so after installing the linux version it all works lol, thanks for help

**Comment by Hypnootize** [comment]
I'm glad it works now! and yeah there are some slight differences between Linux and Windows. Linux seems to manage file paths in a different way so I had to specify the whole path back to the cfg folder for it. From the feedback I got it seems to be working as intended now thankfully.
