### ISSUE TITLE
ammo

### ISSUE THREAD

**Issue by CharlesTXR** [Hypnootize/m0rehud#56]
cant see ammo in hud

**Comment by Hypnootize** [comment]
Is it invisible even if you resetart the game? if the ammo disappears only sometimes then that's a game bug that happens with any HUD, it can be fixed by inspecting a teammate, usually by pressing F while looking at them and then looking away and pressing F again.

**Comment by CharlesTXR** [comment]
sorry for the late reply its working now thanks best customizable hud ever
gng respect


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by CharlesTXR** [comment]
its working now keep up good work best hud ever

**Comment by CharlesTXR** [comment]
thank you for your service
