### ISSUE TITLE
my ammo sometimes dissapear

### ISSUE THREAD

**Issue by weedbird1** [Hypnootize/m0rehud#57]
is there any way to prevent it? (idk how it happens tbh)
![20240627133005_1](https://github.com/Hypnootize/m0rehud/assets/173950985/28f712aa-129c-416f-905a-064760efb96f)

**Comment by Hypnootize** [comment]
I'm not sure why it seems to happen a lot for certain players compared to others but that's a game bug and is not related to the HUD as far as I know. The easiest solution is to simply inspect the items of any of your teammates, by default should be bound to `F` so look at your teammate and press `F`, then look away and press `F` again, in theory that should bring the ammos back, don't ask me why but it usually works.

**Comment by weedbird1** [comment]
oh yeah it happens with a default hud too
thanks for answering
