### ISSUE TITLE
Missing font 'm0refont46' 

### ISSUE THREAD

**Issue by qkeitoe** [Hypnootize/m0rehud#6]
'[Health - Ammo - Uber] Default Style, Small Font' is broken now.
![image](https://user-images.githubusercontent.com/66339491/90331124-f37a2180-dfba-11ea-956d-0edfaf3ede48.png)

**Comment by Hypnootize** [comment]
I meant to make the small health customizations use m0refont48 (since its used a lot more all over the hud while the 46 was only used for that) but I forgot. Should be good now!
