### ISSUE TITLE
ctf icon issue on ctf_haarp

### ISSUE THREAD

**Issue by r3dnasa** [Hypnootize/m0rehud#62]
![20240815125228_1](https://github.com/user-attachments/assets/82b2d240-d777-421b-a918-b2b66a6dc5bb)
icon is offset and big, fixes when you reload hud but not sure why it breaks in the firstplace
![20240815131213_1](https://github.com/user-attachments/assets/7dc83ca2-1a08-4783-889f-1920e5ef5381)
when taking the intel it gets blocked by capture points

**Comment by Hypnootize** [comment]
Should be fixed with the last version
