### ISSUE TITLE
matchmaking settings button is MASSIVE after recent scream fortress update

### ISSUE THREAD

**Issue by dom1643** [Hypnootize/m0rehud#66]
![image](https://github.com/user-attachments/assets/a4d5f870-4072-4c14-9acd-d4b4a0b02977)

**Comment by dom1643** [comment]
![image](https://github.com/user-attachments/assets/e615121c-ebc6-419e-b643-2ac42bce2d09)
all dropdowns are massive, actually

**Comment by georgiesgithub** [comment]
![image](https://github.com/user-attachments/assets/d15571a1-9d29-4e05-9b46-2b49f19e0b36)
Hud is massive on m0rehud classic

**Comment by georgiesgithub** [comment]
![image](https://github.com/user-attachments/assets/d5c857d0-7b1d-4d4a-adbc-baf4b72f8c28)
Loading screen UI at bottom right is also massive

**Comment by Hypnootize** [comment]
Should be all fixed now
